SELECT Produto.ID, Produto.NOME, Estoque.QUANTIDADE_ATUAL, Estoque.QUANTIDADE_MINIMA
FROM Produto
JOIN Estoque ON Produto.ID_ESTOQUE = Estoque.ID
WHERE Estoque.QUANTIDADE_ATUAL < Estoque.QUANTIDADE_MINIMA;
